### ISSUE TITLE
Why do you have your own eth lib?

### ISSUE THREAD

**Issue by calummoore** [spacetimehq/docs#5]
We have our own eth library so that we can expose only the functions needed for our use case. The `web3` and `eth` libraries contain code for a lot of different use cases which increases the build size and makes it harder for users to work out which functions they can use.

**Comment by sdgandhi** [comment]
Added to our FAQ: https://www.notion.so/spacetimexyz/FAQ-Frequently-Asked-Questions-3cd03c49faa247ca817e83ebf6cc62f4

Will make this public on website soon.
